services:
  ros-noetic:
    image: ros_noetic
    privileged: true
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: cont_ros_noetic
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
    volumes:
      # PERMISSIONS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      # WORKSPACE (solo lectura)
      - ./.devcontainer/.vscode:/catkin_ws/.vscode:rw
      # WORKSPACE (lectura y escritura)
      - ./proyecto_ros:/catkin_ws/src
    network_mode: "host"

